namespace CYQ.Entity.MySpace
{
    public enum TableNames
    {
        Blog_Class,
        ErrorLogs,
        Blog_Content,
        Blog_Link,
        Blog_Comment,
        Blog_Skin,
        Blog_GuestBook,
        Blog_GuestRevert,
        Blog_File,
        Blog_User,
        Blog_Visit,
    }
    #region Ã¶¾Ù
    public enum Class
    {
        ID,
        UserID,
        PKey,
        Name,
        CreateTime,
        TypeID,
        Count,
        IsVisible
    }
    public enum ErrorLogs
    {
        ID,
        PageUrl,
        ErrorMessage,
        CreateTime
    }
    public enum Content
    {
        ID,
        ClassID,
        UserID,
        TypeID,
        Title,
        Body,
        Abstract,
        Tag,
        CreateTime,
        Icon,
        ViewLevel,
        ViewPassword,
        CommentLevel,
        CommentCount,
        EditTime,
        Hits,
        IsRss,
        IsPub,
        IsTop,
        IsMain
    }
    public enum Links
    {
        ID,
        UserID,
        Title,
        LinkUrl,
        Body,
        CreateTime
    }
    public enum Comment
    {
        ID,
        ContentUserID,
        ContentID,
        TypeID,
        UserID,
        NickName,
        Body,
        CreateTime
    }
    public enum Skin
    {
        ID,
        UserID,
        Name,
        SkinPath,
        IsEnabled,
        CreateTime
    }
    public enum Files
    {
        ID,
        UserID,
        FileName,
        FilePath,
        Size,
        CreateTime,
        IsTemp
    }
    public enum Users
    {
        ID,
        UserName,
        NickName,
        Password,
        Email,
        SkinID,
        HeadUrl,
        Bulletin,
        Enabled,
        SpaceName,
        SpaceIntro,
        Sign,
        CustomCss,
        ArticleListSize,
        PhotoListSize,
        Amount,
        VisitCount,
        CreateTime
    }
    #endregion
}